spring:
  profiles: 
  active: dev




---
spring:
  profiles: dev
  application:
    name: springcloud-provider

eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
      
---
spring:
  profiles: test
  application:
    name: springcloud-provider

eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/